name: HnH
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  cloud_firestore: ^0.12.1
  firebase_auth: ^0.11.1+5
  google_sign_in: ^3.2.4
  shared_preferences: ^0.5.3
  fluttertoast: ^3.1.0
  firebase_database: ^3.0.2
  connectivity: ^0.4.3+2
  transparent_image: ^1.0.0
  cached_network_image: ^0.8.0
  intro_views_flutter: '^2.6.0'
  google_maps_flutter: ^0.4.0
  firebase_storage: ^3.0.1
  image_picker: ^0.6.0+9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  image_path: "images/launcher_icon.png" 
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/c1.jpg
    - images/m1.jpeg
    - images/m2.jpg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/products/cos1.jpg
    - images/products/cos2.jpg
    - images/products/daily1.jpg
    - images/products/daily2.jpg
    - images/products/fruits1.jpg
    - images/products/fruits2.jpg
    - images/products/med1.jpg
    - images/products/med2.jpg
    - images/products/veg1.jpeg
    - images/products/veg2.jpg
    - images/launcher_icon.png
    - images/cosmetics.png
    - images/daily_goods.png
    - images/fruits.png
    - images/medicines.png
    - images/vegetables.png
    - images/google.png
    - images/background.png
    - images/splash.jpg
    - images/g_logo.png
    - images/daily.png
    - images/med.png
    - images/location.png
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/product_sans_bold.ttf
        - asset: fonts/product_sans_regular.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
